# AUTO-GENERATED by tools/gen_config.py from config_schema.json. DO NOT EDIT.
import ctypes

CONFIG_ABI_VERSION = 2

CONFIG_FIELDS = [
    ("n_groups_tokens", ctypes.c_uint32),
    ("region_cnt", ctypes.c_uint32),
    ("region_size_pages", ctypes.c_uint64),
    ("epoch_secs", ctypes.c_uint32),
    ("gc_high_water_pct", ctypes.c_uint32),
    ("hot_hit_threshold", ctypes.c_uint32),
    ("hot_decay_ms", ctypes.c_uint32),
    ("sync_mode", ctypes.c_bool),
    ("journal_pages", ctypes.c_uint32),
    ("stripe_threshold", ctypes.c_uint64),
    ("metrics_level", ctypes.c_uint8),
    ("gc_start_pct", ctypes.c_uint32),
    ("gc_stop_pct", ctypes.c_uint32),
    ("gc_step_gens", ctypes.c_uint32),
    ("min_gen_age_secs", ctypes.c_uint32),
    ("evict_tomb_cap", ctypes.c_uint32),
    ("max_layers", ctypes.c_uint32),
    ("batch_min_bytes", ctypes.c_uint32),
    ("dram_cache_bytes", ctypes.c_uint64),
    ("dram_entry_max_bytes", ctypes.c_uint64),
    ("dram_alloc_backend", ctypes.c_uint8),
    ("dram_cache_side", ctypes.c_uint8),
    ("stripe_unit", ctypes.c_uint64),
    ("region_align_bytes", ctypes.c_uint64),
    ("abi_version", ctypes.c_uint32),
    ("abi_size", ctypes.c_uint32),
]
