/* AUTO-GENERATED by tools/gen_config.py from config_schema.json. DO NOT EDIT. */
#define KV_CONFIG_ABI_VERSION 2
#define KV_CONFIG_APPLY_DEFAULTS(cfg) do { \
    (cfg)->n_groups_tokens = KV_TOKENS_PER_GROUP; \
    (cfg)->region_cnt = 6; \
    (cfg)->region_size_pages = 0; \
    (cfg)->epoch_secs = 1800; \
    (cfg)->gc_high_water_pct = 10; \
    (cfg)->hot_hit_threshold = 64; \
    (cfg)->hot_decay_ms = 10000; \
    (cfg)->sync_mode = false; \
    (cfg)->journal_pages = 512; \
    (cfg)->stripe_threshold = KV_STRIPE_THRESHOLD; \
    (cfg)->metrics_level = 1; \
    (cfg)->gc_start_pct = 80; \
    (cfg)->gc_stop_pct = 70; \
    (cfg)->gc_step_gens = 1; \
    (cfg)->min_gen_age_secs = 0; \
    (cfg)->evict_tomb_cap = 65536; \
    (cfg)->max_layers = KV_MAX_LAYERS_CAP; \
    (cfg)->batch_min_bytes = KV_BATCH_MIN_BYTES; \
    (cfg)->dram_cache_bytes = KV_DRAM_DEFAULT_BYTES; \
    (cfg)->dram_entry_max_bytes = KV_DRAM_DEFAULT_ENTRY_MAX; \
    (cfg)->dram_alloc_backend = 0; \
    (cfg)->dram_cache_side = 0; \
    (cfg)->stripe_unit = 0; \
    (cfg)->region_align_bytes = 0; \
    (cfg)->abi_version = KV_CONFIG_ABI_VERSION; \
    (cfg)->abi_size = sizeof(struct kv_config); \
} while (0)
