/* AUTO-GENERATED by tools/gen_config.py from config_schema.json. DO NOT EDIT. */
#ifndef KV_CONFIG_GEN_H
#define KV_CONFIG_GEN_H
    uint32_t n_groups_tokens;       /* tokens per KV group */
    uint32_t region_cnt;            /* number of regions */
    uint64_t region_size_pages;     /* 0 => auto from device capacity */
    uint32_t epoch_secs;            /* generation epoch seconds */
    uint32_t gc_high_water_pct;     /* legacy gc high-water pct */
    uint32_t hot_hit_threshold;     /* hotness upgrade threshold */
    uint32_t hot_decay_ms;          /* hotness decay window ms */
    bool     sync_mode;             /* put acks wait for fua/fsync */
    uint32_t journal_pages;         /* per-device journal size pages */
    uint64_t stripe_threshold;      /* 0 => default; bytes triggering stripe split */
    uint8_t  metrics_level;         /* 0 off / 1 counters / 2 +histograms */
    uint32_t gc_start_pct;          /* generational GC trigger pct */
    uint32_t gc_stop_pct;           /* GC hysteresis stop pct */
    uint32_t gc_step_gens;          /* max generations dropped per tick */
    uint32_t min_gen_age_secs;      /* minimum evictable generation age */
    uint32_t evict_tomb_cap;        /* evicted-key tombstone slots (pow2) */
    uint32_t max_layers;            /* runtime per-group layer limit */
    uint32_t batch_min_bytes;       /* 0 => default; group-commit batch floor */
    uint64_t dram_cache_bytes;      /* DRAM read cache budget */
    uint64_t dram_entry_max_bytes;  /* 0 => default; skip larger entries */
    uint8_t  dram_alloc_backend;    /* 0 auto / 1 plain / 2 thp / 3 hugetlb */
    uint8_t  dram_cache_side;       /* reserved: 0 consumer / 1 storage */
    uint64_t stripe_unit;           /* 0 => KV_STRIPE_UNIT; stripe slice bytes */
    uint64_t region_align_bytes;    /* 0 => page; region capacity alignment */
    uint32_t abi_version;           /* ABI version (appended last) */
    uint32_t abi_size;              /* sizeof(kv_config) at build time */
#endif /* KV_CONFIG_GEN_H */
