#!/usr/bin/env python3
"""Generate kv_config C struct/defaults and the Python ctypes field list
from tools/config_schema.json.

Single source of truth = the schema.  Run after editing the schema:
    python3 tools/gen_config.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # solidcacher/
REPO = os.path.dirname(ROOT)                       # repo root
SCHEMA = os.path.join(HERE, "config_schema.json")

GEN_H = os.path.join(ROOT, "include", "kv_config_gen.h")
DEF_H = os.path.join(ROOT, "include", "kv_config_defaults.h")
PY_F = os.path.join(REPO, "adapters", "sglang", "solidcacher_py",
                    "_config_fields.py")

BANNER = "/* AUTO-GENERATED by tools/gen_config.py from config_schema.json. DO NOT EDIT. */"


def load():
    with open(SCHEMA) as f:
        return json.load(f)


def gen_struct(schema):
    out = [BANNER, "#ifndef KV_CONFIG_GEN_H", "#define KV_CONFIG_GEN_H"]
    for f in schema["fields"]:
        out.append("    %-8s %-22s /* %s */"
                   % (f["c_type"], f["name"] + ";", f["doc"]))
    out += ["#endif /* KV_CONFIG_GEN_H */", ""]
    return "\n".join(out)


def gen_defaults(schema):
    out = [BANNER]
    out.append("#define KV_CONFIG_ABI_VERSION %d" % schema["abi_version"])
    out.append("#define KV_CONFIG_APPLY_DEFAULTS(cfg) do { \\")
    for f in schema["fields"]:
        out.append("    (cfg)->%s = %s; \\" % (f["name"], f["default"]))
    out.append("} while (0)")
    out.append("")
    return "\n".join(out)


def gen_py(schema):
    out = ["# AUTO-GENERATED by tools/gen_config.py from config_schema.json. DO NOT EDIT.",
           "import ctypes", "",
           "CONFIG_ABI_VERSION = %d" % schema["abi_version"], "",
           "CONFIG_FIELDS = ["]
    for f in schema["fields"]:
        out.append('    ("%s", ctypes.%s),' % (f["name"], f["py_type"]))
    out += ["]", ""]
    return "\n".join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print("wrote %s" % os.path.relpath(path, REPO))


def main():
    schema = load()
    write(GEN_H, gen_struct(schema))
    write(DEF_H, gen_defaults(schema))
    write(PY_F, gen_py(schema))
    return 0


if __name__ == "__main__":
    sys.exit(main())
